# Generated by Django 2.0.5 on 2019-01-10 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='account',
            name='createdBy',
        ),
    ]
