# Generated by Django 2.1.5 on 2019-02-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190110_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='website',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Website'),
        ),
    ]
